version: 3
workdir: internal

components:
  bootstrap:
    in: bootstrap/**
  controller:
    in: controller/**
  usecase:
    in: usecase/**
  service:
    in: service/**
  statemachine:
    in: statemachine/**
  jobio:
    in: jobio/**
  repository:
    in: repository/**
  infra_ai:
    in: infra/ai/**
  infra_runtime:
    in: infra/runtime/**
  infra_sqlite:
    in: infra/sqlite/**

deps:
  bootstrap:
    deepScan: false
    mayDependOn:
      - controller
      - usecase
      - service
      - repository
      - infra_ai
  controller:
    mayDependOn:
      - usecase
  usecase:
    mayDependOn:
      - service
      - statemachine
      - jobio
  service:
    deepScan: false
    mayDependOn:
      - repository
  jobio:
    mayDependOn:
      - repository
  repository:
    mayDependOn:
      - infra_runtime
      - infra_sqlite
  infra_ai:
    mayDependOn:
      - infra_runtime
allow:
  depOnAnyVendor: true
