sonar.projectKey=ishibata91_AITranslationEngineJP
sonar.projectName=AITranslationEngineJP
sonar.organization=ishibata91
sonar.sources=src,src-tauri
sonar.test.inclusions=**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/target/**
sonar.sourceEncoding=UTF-8
