sonar.projectKey=ishibata91_AITranslationEngineJP
sonar.projectName=AITranslationEngineJP
sonar.organization=ishibata91
sonar.sources=src,src-tauri/src,src-tauri/build.rs
sonar.test.inclusions=src/**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/target/**,**/target/debug/**,**/target/debug/deps/**,**/*.rmeta,src-tauri/gen/**,src-tauri/icons/**
sonar.sourceEncoding=UTF-8
