import type { PersonaGenerationPhaseScreenViewModel } from "@application/contract/persona-generation-phase"

export const personaGenerationPhasePanelFixture: PersonaGenerationPhaseScreenViewModel =
  {
    jobId: 101,
    phase: "ready",
    summary: null,
    bodyReadiness: null,
    errorMessage: "",
    pendingAction: null,
    hasLoaded: true,
    gatewayStatus: "接続済み",
    viewState: "not_started",
    isLoading: false,
    isRefreshing: false,
    isSubmitting: false,
    hasJobSelection: true,
    currentPhaseLabel: "NPC ペルソナ生成",
    phaseStateLabel: "未開始",
    statusTitle: "NPC ペルソナ生成を開始できます",
    statusText: "NPC ペルソナ生成用の AI 設定を確認してから開始します。",
    progressPercent: 0,
    progressLabel: "0 / 96",
    progressDetail: "開始待ち",
    startedAtLabel: "-",
    finishedAtLabel: "-",
    targetCountLabel: "96",
    generatedCountLabel: "0",
    failedCountLabel: "0",
    skippedCountLabel: "8",
    npcCountLabel: "96",
    commonPersonaHitCountLabel: "24",
    commonPersonaMissCountLabel: "72",
    skippedReasonsLabel: "翻訳対象外 8 件",
    targetSnapshotLabel: "-",
    providerLabel: "OpenAI",
    modelLabel: "gpt-4.1-mini",
    executionModeLabel: "通常実行",
    credentialRefLabel: "認証済み",
    inputCountLabel: "96",
    outputCountLabel: "一括処理なし",
    evidenceRefsLabel: "-",
    promptDigestLabel: "-",
    snapshotLabel: "-",
    snapshotReferenceStatusLabel: "-",
    personaCountLabel: "0",
    missingCountLabel: "96",
    bodyReadinessLabel: "NPC ペルソナ生成の完了後に確認できます",
    bodyReadinessBlockedReason: "NPC ペルソナ生成が未完了です。",
    bodyReadinessInputSummaryLabel: "本文翻訳の入力は未作成です。",
    errorKindLabel: "-",
    errorReasonLabel: "-",
    retryableLabel: "-",
    actionCards: [
      {
        id: "start",
        label: "開始",
        disabled: false,
        blockedReason: "",
        tone: "primary"
      },
      {
        id: "pause",
        label: "中断",
        disabled: true,
        blockedReason: "実行中ではありません。",
        tone: "default"
      }
    ],
    screenActionEnablement: {
      canRefresh: true,
      canStart: true,
      canPause: false,
      canResume: false,
      canRetry: false,
      canCancel: false,
      canCheckBodyReadiness: false,
      canStartBodyPhase: false
    },
    lastErrorSummary: null,
    actionEnablement: null,
    latestProgressSummary: null,
    latestTargetSummary: null,
    latestResultSummary: null,
    latestExecutionSummary: null,
    latestErrorKind: null,
    latestBodyReadiness: null,
    latestBodyReadinessInputSummary: null
  }
