import type {
  ProcessingTargetListRequest,
  ProcessingTargetListResponse
} from "@application/gateway-contract/processing-target"
import type {
  CancelPersonaGenerationPhaseRequest,
  GetPersonaGenerationBodyReadinessRequest,
  GetPersonaGenerationPhaseSummaryRequest,
  PausePersonaGenerationPhaseRequest,
  PersonaGenerationBodyReadinessResponse,
  PersonaGenerationPhaseCommandResponse,
  PersonaGenerationPhaseAISettingsRequest,
  PersonaGenerationPhaseAISettingsResponse,
  PersonaGenerationPhaseFetchResponse,
  ResumePersonaGenerationPhaseRequest,
  RetryPersonaGenerationPhaseRequest,
  StartPersonaGenerationPhaseRequest
} from "@application/gateway-contract/persona-generation-phase"

export type GetProcessingTargetListRequestDto = ProcessingTargetListRequest
export type GetProcessingTargetListResponseDto = ProcessingTargetListResponse

export type GetPersonaGenerationPhaseSummaryRequestDto =
  GetPersonaGenerationPhaseSummaryRequest
export type GetPersonaGenerationPhaseSummaryResponseDto =
  PersonaGenerationPhaseFetchResponse

export type StartPersonaGenerationPhaseRequestDto =
  StartPersonaGenerationPhaseRequest
export type StartPersonaGenerationPhaseResponseDto =
  PersonaGenerationPhaseCommandResponse

export type SavePersonaGenerationPhaseAISettingsRequestDto =
  PersonaGenerationPhaseAISettingsRequest
export type SavePersonaGenerationPhaseAISettingsResponseDto =
  PersonaGenerationPhaseAISettingsResponse

export type PausePersonaGenerationPhaseRequestDto =
  PausePersonaGenerationPhaseRequest
export type PausePersonaGenerationPhaseResponseDto =
  PersonaGenerationPhaseCommandResponse

export type ResumePersonaGenerationPhaseRequestDto =
  ResumePersonaGenerationPhaseRequest
export type ResumePersonaGenerationPhaseResponseDto =
  PersonaGenerationPhaseCommandResponse

export type RetryPersonaGenerationPhaseRequestDto =
  RetryPersonaGenerationPhaseRequest
export type RetryPersonaGenerationPhaseResponseDto =
  PersonaGenerationPhaseCommandResponse

export type CancelPersonaGenerationPhaseRequestDto =
  CancelPersonaGenerationPhaseRequest
export type CancelPersonaGenerationPhaseResponseDto =
  PersonaGenerationPhaseCommandResponse

export type GetPersonaGenerationBodyReadinessRequestDto =
  GetPersonaGenerationBodyReadinessRequest
export type GetPersonaGenerationBodyReadinessResponseDto =
  PersonaGenerationBodyReadinessResponse
