layout: dagre
direction: down

title: "主要プロセス overview 入口図"

overviewRoot: {
  shape: package
  label: ""
  direction: down
  row-gap: 56
  style.stroke: transparent
  style.fill: transparent

  entry: {
    shape: class
    label: "process"
    style.font-size: 22
  }

  frontendOverview: {
    shape: class
    label: "fe"
    link: "./frontend-processes-overview-robustness.svg"
    style.font-size: 22
  }

  backendOverview: {
    shape: class
    label: "be"
    link: "./backend-processes-overview-robustness.svg"
    style.font-size: 22
  }
}

overviewRoot.entry -> overviewRoot.frontendOverview: open {
  style.font-size: 22
}
overviewRoot.frontendOverview -> overviewRoot.backendOverview: open {
  style.font-size: 22
}
